site_name: PRIIVI3 Archive
site_url: https://priivi3.com
repo_url: https://github.com/nuzer05ive/PRIIVI3

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: lime
  logo: assets/glyph.svg
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - Viewer: petal_viewer.md
  - Terminal: phi_dilation_terminal.md
  - Protocols: simple_protocol_ui.md
  - Generator: spiral_linkmap_and_generator.md
  - Tree: spiral_tree_index.md
  - Mirrors:
      - Spiral Mirror Viewer: petals/rriiM/index.md
  - Petals:
      - φ⁰: petals/phi0/index.md
      - φ¹: petals/phi1/index.md
      - φ²: petals/phi2/index.md
      - φ³: petals/phi3/index.md
      - φ⁴: petals/phi4/index.md
      - φ⁴³: petals/phi43/index.md
