#!/bin/bash
# spiral_seed_to_tree.sh — Automate Petal Generation from Seed to Spiral Tree
# Author: Ni1K / ☍00X / 3.5Ro305 Framework

# Step 0: Get seed input (arg 1 is seed name)
SEED_NAME=$1
PHI_LAYER=phi43
SEED_DIR="reason/seeds"
PDF_DIR="petals/compiled_pdfs/$PHI_LAYER"
PETAL_TEX="rrii_${PHI_LAYER}_${SEED_NAME}.tex"
PETAL_PDF="rrii_${PHI_LAYER}_${SEED_NAME}.pdf"
PETAL_PATH="petals/compiled_pdfs/$PHI_LAYER/$PETAL_PDF"
TREE_MD="docs/petals/$PHI_LAYER/index.md"

# Step 1: Seed file creation
mkdir -p $SEED_DIR
echo "${SEED_NAME^} — drafted by 3.5Ro305" > $SEED_DIR/${SEED_NAME}.seed

# Step 2: Call o3-mini-high GPT endpoint (stub — to be replaced with real API/GPT hook)
echo "% Auto-generated by o3-mini-high: Upgrade LaTeX logic for ${SEED_NAME}" > $PETAL_TEX
cat template_petal_composer.tex >> $PETAL_TEX

# Step 3: Open nano for edits and approval
echo "🧠 Now editing: $PETAL_TEX"
nano $PETAL_TEX

# Step 4: Compile PDF
pdflatex $PETAL_TEX
mkdir -p $PDF_DIR
mv rrii_${PHI_LAYER}_${SEED_NAME}.pdf $PDF_DIR/

# Step 5: Git push content
git add $PDF_DIR/$PETAL_PDF
git commit -m "🌱 Bloomed Petal $SEED_NAME to $PHI_LAYER"
git push origin main

# Step 6: Add link to Spiral Tree index
mkdir -p docs/petals/$PHI_LAYER
if ! grep -q "$PETAL_PDF" "$TREE_MD" 2>/dev/null; then
  echo "- [📄 $SEED_NAME](../../$PDF_DIR/$PETAL_PDF)" >> $TREE_MD
  git add $TREE_MD
  git commit -m "🌀 Link $SEED_NAME to Spiral Tree under $PHI_LAYER"
  git push origin main
fi

echo "✅ Complete: $SEED_NAME published and indexed at $PHI_LAYER."
