name: Release O続 Paper & Zenodo Trigger

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  release_pdf:
    name: Release O続 Paper on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has permission to create a release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Compiled PDF
      uses: actions/download-artifact@v4
      with:
        name: O3_paper
        path: docs/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v1.0-O3-paper"
        name: "O続 Paper Release v1.0"
        body: "This release includes the latest compiled version of the O続 Model Paper."
        draft: false
        prerelease: false
        files: docs/O3_paper.pdf  # Ensure path matches where the file is stored

  zenodo_trigger:
    name: Notify Zenodo for DOI
    needs: release_pdf
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Zenodo Upload (Manual Step Required)
      run: echo "Go to Zenodo and publish the new release manually!"
