name: Validate LaTeX & BibTeX

on:
  pull_request:
    paths:
      - "docs/**/*.tex"
      - "docs/**/*.bib"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (Updated for v4)
        uses: actions/checkout@v4

      - name: Install LaTeX & BibTeX
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra

      - name: Validate LaTeX Syntax
        run: |
          for file in docs/*/*.tex; do
            folder=$(dirname "$file")
            filename=$(basename "$file" .tex)
            echo "Checking $file..."
            latexmk -lualatex -cd -interaction=nonstopmode -halt-on-error "$folder/$filename.tex" || exit 1
          done

      - name: Validate BibTeX References
        run: |
          for file in docs/*/*.bib; do
            folder=$(dirname "$file")
            filename=$(basename "$file" .bib)
            echo "Validating BibTeX in $file..."
            bibtex "$folder/$filename"
          done
